defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node

version: 2
jobs:
  install:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Installing node modules
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: "~"
          paths:
            - repo

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: "~"

      - run:
          name: Linting
          command: npm lint

      - run:
          name: Testing
          command: npm test

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: "~"

      - run:
          name: Building
          command: npm build

  publish:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  publish:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          filters:
            branches:
              only:
                - master
          requires:
            - test
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
